import ActivityKit
import Foundation
import PamNative
public final class LiveActivitiesModule:NativeModule,@unchecked Sendable{public init(){};public func invoke(method:String,payload:Data,completion:@escaping ModuleCompletion){do{let v=try WireMap.decode(payload);switch method{case"start":try start(v,completion);case"update":update(v,completion);case"end":end(v,completion);case"active":try active(completion);default:failure("Unknown method: \(method)",completion)}}catch{failure(String(describing:error),completion)}}
 private func start(_ v:[String:WireValue],_ completion:ModuleCompletion)throws{guard ActivityAuthorizationInfo().areActivitiesEnabled else{throw LiveError.disabled};let attributes=PamLiveActivityAttributes(key:try v.text("key"));let activity=try Activity.request(attributes:attributes,content:ActivityContent(state:try state(v),staleDate:nil),pushType:v.flag("pushEnabled") ? .token:nil);try success(["identifier":.text(activity.id)],completion)}
 private func update(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion){Task{do{guard let activity=try find(v)else{throw LiveError.notFound};await activity.update(ActivityContent(state:try state(v),staleDate:nil));try success(["identifier":.text(activity.id)],completion)}catch{failure(String(describing:error),completion)}}}
 private func end(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion){Task{do{guard let activity=try find(v)else{throw LiveError.notFound};await activity.end(ActivityContent(state:try state(v),staleDate:nil),dismissalPolicy:v.flag("immediate") ? .immediate:.default);try success(["identifier":.text(activity.id)],completion)}catch{failure(String(describing:error),completion)}}}
 private func active(_ completion:ModuleCompletion)throws{let rows=Activity<PamLiveActivityAttributes>.activities.map{activity in["identifier":activity.id,"key":activity.attributes.key,"pushToken":activity.pushToken?.map{String(format:"%02x",$0)}.joined() ?? "","state":stateCode(activity.activityState)]as[String:Any]};let data=try JSONSerialization.data(withJSONObject:rows);try success(["json":.text(String(data:data,encoding:.utf8) ?? "[]")],completion)}
 private func find(_ v:[String:WireValue])throws->Activity<PamLiveActivityAttributes>?{let id=try v.text("identifier");return Activity<PamLiveActivityAttributes>.activities.first{$0.id==id}};private func state(_ v:[String:WireValue])throws->PamLiveActivityAttributes.ContentState{.init(title:try v.text("title"),status:try v.text("status"),progress:max(0,min(1,try v.decimal("progress"))),deepLink:try v.text("deepLink"))};private func stateCode(_ state:ActivityState)->Int{switch state{case.active:return 1;case.ended:return 2;case.dismissed:return 3;case.stale:return 4;@unknown default:return 4}};private func success(_ values:[String:WireValue],_ completion:ModuleCompletion)throws{completion(.success,try WireMap.encode(values))};private func failure(_ m:String,_ completion:ModuleCompletion){completion(.failure,Data(m.prefix(1024).utf8))}}
private enum LiveError:Error{case disabled;case notFound};private extension Dictionary where Key==String,Value==WireValue{func text(_ k:String)throws->String{guard case let.text(v)?=self[k]else{throw LiveError.notFound};return v};func flag(_ k:String)->Bool{if case let.flag(v)?=self[k]{return v};return false};func decimal(_ k:String)throws->Double{switch self[k]{case let.decimal(v)?:return v;case let.integer(v)?:return Double(v);default:throw LiveError.notFound}}}
